"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";

type Status="idle"|"connecting"|"connected"|"error"; type Mode="listening"|"speaking"; type Session={endSession:()=>Promise<void>|void};
type Turn={role:"user"|"assistant";content:string};
export function HablarConEon(){
 const [status,setStatus]=useState<Status>("idle"),[mode,setMode]=useState<Mode>("listening"),[error,setError]=useState(""),[caption,setCaption]=useState(""),[usingCloned,setUsingCloned]=useState(false),[hasClonedVoice,setHasClonedVoice]=useState<boolean|null>(null),[turns,setTurns]=useState<Turn[]>([]);
 const sessionRef=useRef<Session|null>(null),turnsRef=useRef<Turn[]>([]);
 const flushTranscript=useCallback(()=>{const t=turnsRef.current;turnsRef.current=[];if(!t.length)return;const body=JSON.stringify({turns:t});try{if(navigator.sendBeacon?.('/api/voice/transcript',new Blob([body],{type:'application/json'})))return}catch{}void fetch('/api/voice/transcript',{method:'POST',headers:{'Content-Type':'application/json'},body,keepalive:true}).catch(()=>{})},[]);
 const stop=useCallback(async()=>{try{await sessionRef.current?.endSession()}catch{}sessionRef.current=null;flushTranscript();setStatus('idle');setMode('listening')},[flushTranscript]);
 useEffect(()=>()=>{void stop()},[stop]);useEffect(()=>{fetch('/api/voice/clone').then(r=>r.json()).then(d=>setHasClonedVoice(Boolean(d.voiceId))).catch(()=>setHasClonedVoice(null))},[]);
 async function start(){setError('');setStatus('connecting');setCaption('');setTurns([]);try{await navigator.mediaDevices.getUserMedia({audio:true});const r=await fetch('/api/voice/agent',{method:'POST'});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo iniciar');setUsingCloned(Boolean(d.usingClonedVoice));const {Conversation}=await import('@elevenlabs/client');const session=await Conversation.startSession({signedUrl:d.signedUrl,overrides:d.overrides,onConnect:()=>setStatus('connected'),onDisconnect:()=>{setStatus('idle');setMode('listening');flushTranscript()},onError:(x:unknown)=>{setError(String(x));setStatus('error')},onModeChange:(x:{mode:Mode})=>setMode(x.mode),onMessage:(m:{message:string;source:string})=>{if(!m?.message)return;const turn:Turn={role:m.source==='user'?'user':'assistant',content:m.message};setCaption(m.message);turnsRef.current.push(turn);setTurns(v=>[...v,turn].slice(-6))}});sessionRef.current=session as unknown as Session}catch(e){setError(e instanceof Error&&e.name==='NotAllowedError'?'Necesito permiso de micrófono para escucharte.':e instanceof Error?e.message:'No se pudo iniciar');setStatus('error')}}
 const active=status==='connected',speaking=active&&mode==='speaking';
 return <div className="eon-voice-stage"><div className={`eon-live-field ${active?'is-active':''} ${speaking?'is-speaking':''}`} aria-hidden><span/><span/><span/><span/></div><p className="eon-kicker">Eon · voz en vivo</p><h1>{status==='connecting'?'Preparando Eon…':active?speaking?'Eon está hablando':'Tu turno':'Habla con Eon'}</h1><p className="eon-sub">Una conversación, no un dictado. Puedes interrumpir, cambiar de tema y hablar a tu ritmo.</p><motion.button type="button" onClick={active||status==='connecting'?stop:start} className="eon-live-button" whileTap={{scale:.96}} aria-label={active?'Terminar conversación':'Hablar con Eon'}>{status==='connecting'?<span className="loader"/>:active?<span className="stop-square"/>:<span className="voice-bars"><i/><i/><i/></span>}</motion.button><div className="eon-live-status">{status==='idle'&&'Toca para comenzar'}{status==='connecting'&&'Conectando voz y memoria'}{active&&(speaking?'Escucha o interrumpe cuando quieras':'Escuchando')}{status==='error'&&error}</div>{caption&&active?<p className="eon-live-caption">{caption}</p>:null}{turns.length>1&&active?<div className="voice-turns">{turns.slice(-4).map((t,i)=><p key={i} className={t.role}><b>{t.role==='user'?'Tú':'Eon'}</b>{t.content}</p>)}</div>:null}{hasClonedVoice===false?<a href="/app/perfil" className="eon-live-link">Crear mi voz →</a>:null}{active&&usingCloned?<p className="eon-live-note">Eon está usando tu clon de voz.</p>:null}</div>;
}
