"use client";
import { useEffect, useRef, useState } from "react";
import { FadeInOnScroll } from "@/components/motion";
import { Button, Card, CardDescription, CardTitle } from "@/components/ui";
import { uploadFile } from "@/lib/upload-client";

type Pose={id:string;label:string};
const POSES:Pose[]=[{id:"front",label:"Frente · expresión neutra"},{id:"three_left",label:"Tres cuartos izquierdo"},{id:"left",label:"Perfil izquierdo"},{id:"three_right",label:"Tres cuartos derecho"},{id:"right",label:"Perfil derecho"},{id:"smile",label:"Sonrisa natural"}];
type Asset={id:string;pose:string;blobUrl:string};
export function IdentityCapture(){
 const input=useRef<HTMLInputElement>(null),videoInput=useRef<HTMLInputElement>(null);const [assets,setAssets]=useState<Asset[]>([]),[working,setWorking]=useState(false),[err,setErr]=useState("");
 useEffect(()=>{fetch('/api/identity').then(r=>r.json()).then(d=>setAssets(d.assets||[])).catch(()=>{})},[]);
 const done=new Set(assets.map(a=>a.pose));const next=POSES.find(p=>!done.has(p.id));
 async function onFile(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f||!next)return;setWorking(true);setErr("");try{try{const bmp=await createImageBitmap(f);if(Math.min(bmp.width,bmp.height)<720){bmp.close();throw new Error('La foto necesita más resolución. Acércate y vuelve a tomarla.')}bmp.close()}catch(q){if(q instanceof Error&&q.message.includes('resolución'))throw q}const u=await uploadFile(f,'file',`Identidad visual · ${next.label}`);const r=await fetch('/api/identity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:u.url,pose:next.id,mime:f.type,consent:true})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No pude guardar');setAssets(v=>[...v,d.asset]);}catch(x){setErr(x instanceof Error?x.message:'No pude guardar esta captura.')}finally{setWorking(false);if(input.current)input.current.value=''}}
 async function onVideo(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;setWorking(true);setErr('');try{const u=await uploadFile(f,'file','Identidad visual · video de presencia');const r=await fetch('/api/identity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:u.url,pose:'motion',mime:f.type,consent:true})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No pude guardar el video');setAssets(v=>[...v.filter(x=>x.pose!=='motion'),d.asset])}catch(x){setErr(x instanceof Error?x.message:'No pude guardar el video.')}finally{setWorking(false);if(videoInput.current)videoInput.current.value=''}}
 async function reset(){for(const a of assets)await fetch('/api/identity?id='+encodeURIComponent(a.id),{method:'DELETE'});setAssets([])}
 return <FadeInOnScroll delay={.16}><Card><input ref={input} hidden type="file" accept="image/*" capture="user" onChange={onFile}/><input ref={videoInput} hidden type="file" accept="video/*" capture="user" onChange={onVideo}/><div className="identity-capture va-crystal va-spatial"><div><p className="eon-page-kicker">Identidad visual</p><CardTitle>Guarda cómo eres hoy.</CardTitle><CardDescription className="mt-1">Seis ángulos privados preparan tu archivo visual para futuras funciones de presencia digital. Eternime no crea un avatar ni usa estas fotos fuera de tu cuenta sin una autorización posterior.</CardDescription></div><div className="identity-progress"><span style={{width:`${Math.round(done.size/POSES.length*100)}%`}}/></div>{next?<div className="identity-shot"><div className="identity-face-guide"><span/><i/></div><div><small>Captura {done.size+1} de {POSES.length}</small><h3>{next.label}</h3><p>Luz frontal, sin filtros, rostro completo y fondo sencillo.</p><Button onClick={()=>input.current?.click()} loading={working}>Abrir cámara</Button></div></div>:<div className="identity-done"><span>✓</span><div><b>Base visual completa</b><small>{assets.length} ángulos guardados en tu tenant privado.</small></div><div className="flex flex-wrap gap-2"><Button variant="ghost" onClick={()=>videoInput.current?.click()} loading={working}>{assets.some(x=>x.pose==='motion')?'Regrabar video':'Grabar video de presencia'}</Button><Button variant="ghost" onClick={reset}>Rehacer</Button></div></div>}{!next&&<p className="identity-video-note">Video opcional: 10–20 segundos mirando a cámara, girando ligeramente el rostro y diciendo una frase natural. Ayuda a conservar movimiento y expresión para futuras funciones.</p>}{err&&<p className="text-sm text-[var(--et-danger)]">{err}</p>}<div className="identity-checks">{POSES.map((p,i)=><span key={p.id} className={done.has(p.id)?'done':next?.id===p.id?'active':''}>{done.has(p.id)?'✓':i+1} · {p.label}</span>)}</div></div></Card></FadeInOnScroll>;
}
