"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";

type Person={id:string;name:string;email?:string|null;phone?:string|null;company?:string|null;role?:string|null;relationship?:string|null;skills?:string[];source?:string};
type Connection={provider:string;provider_user_name?:string|null;last_synced_at?:string|null};
const skills=["Finanzas","Real estate","Tecnología","Legal","Diseño","Ventas"];
export function NetworkClient(){
 const [people,setPeople]=useState<Person[]>([]); const [connections,setConnections]=useState<Connection[]>([]); const [q,setQ]=useState(""); const [importing,setImporting]=useState(false); const [notice,setNotice]=useState(""); const fileRef=useRef<HTMLInputElement|null>(null);
 const load=()=>Promise.all([fetch('/api/network').then(r=>r.ok?r.json():{}),fetch('/api/social/connections').then(r=>r.ok?r.json():{})]).then(([rawP,rawS])=>{const p=rawP as {people?:Person[]};const s=rawS as {connections?:Connection[]};setPeople(p.people||[]);setConnections(s.connections||[])}).catch(()=>{});
 useEffect(()=>{void load()},[]);
 const filtered=useMemo(()=>{const x=q.toLowerCase().trim();if(!x)return people;return people.filter(p=>`${p.name} ${p.relationship||''} ${p.email||''} ${p.phone||''} ${p.company||''} ${p.role||''} ${(p.skills||[]).join(' ')}`.toLowerCase().includes(x))},[people,q]);
 const importVcard=async(file:File)=>{setImporting(true);setNotice("");try{const vcard=await file.text();const r=await fetch('/api/network/import-vcard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({vcard,consent:true})});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo importar');setNotice(`${d.imported||0} contactos incorporados a Mi Red.`);await load();}catch(e){setNotice(e instanceof Error?e.message:'No se pudo importar');}finally{setImporting(false);if(fileRef.current)fileRef.current.value='';}};
 return <>
  <section className="network-search va-crystal va-spatial"><div className="network-signal" aria-hidden><i/><i/><i/></div><div><p className="eon-page-kicker">Pregúntale a tu red</p><h2>¿A quién necesitas encontrar?</h2><p>Busca por persona, relación, empresa o capacidad. Eon va enriqueciendo estos caminos con evidencia.</p></div><label><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ej. alguien que sepa de finanzas…"/></label><div className="network-skills">{skills.map(s=><button key={s} onClick={()=>setQ(s)}>{s}</button>)}</div></section>
  <section className="network-import"><div><p className="eon-page-kicker">Importar contactos</p><h3>Trae tu red sin entregar tu agenda completa a terceros.</h3><p>Exporta o selecciona contactos como archivo VCF. Eternime los guarda privados por defecto y registra tu consentimiento.</p></div><div className="network-import-actions"><input ref={fileRef} type="file" accept=".vcf,text/vcard,text/x-vcard" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importVcard(f)}}/><button onClick={()=>fileRef.current?.click()} disabled={importing}>{importing?'Importando…':'Importar VCF'}</button><Link href="/privacidad">Cómo protegemos tu red</Link></div>{notice&&<p className="network-notice">{notice}</p>}</section>
  <section className="network-canvas va-crystal"><div className="network-center"><span className="eon-mark"/><b>Tú</b></div>{filtered.slice(0,8).map((p,i)=><div key={p.id} className={`network-node n${i%8}`}><span>{p.name?.[0]||'·'}</span><b>{p.name}</b><small>{p.role||p.relationship||p.company||'contacto directo'}</small></div>)}{!filtered.length&&<div className="network-empty">Tu grafo empieza vacío a propósito.<br/>Importa contactos o <Link href="/app/beneficiarios">agrega personas manualmente</Link>.</div>}</section>
  <div className="grid gap-3 sm:grid-cols-2"><section className="network-panel"><p className="eon-page-kicker">Fuentes conectadas</p><h3>Tu contexto social</h3>{connections.length?connections.map(c=><div className="network-source" key={c.provider}><span>✓</span><div><b>{c.provider}</b><small>{c.provider_user_name||'Conectado'}</small></div></div>):<p className="network-muted">Facebook e Instagram se pueden conectar cuando quieras. WhatsApp se integra por actividad autorizada, no aspirando tu agenda o chats privados.</p>}</section><section className="network-panel"><p className="eon-page-kicker">Privacidad</p><h3>Privado por defecto.</h3><p className="network-muted">Cada nodo conserva fuente, confianza y visibilidad. Una inferencia de Eon nunca se presenta como hecho confirmado.</p></section></div>
 </>;
}
