"use client";
import { useEffect, useRef, useState } from "react";
import { FadeInOnScroll } from "@/components/motion";
import { Button, Card, CardDescription, CardTitle } from "@/components/ui";

const PROMPTS=[
  "Di tu nombre y cuéntame cómo fue tu día, como si hablaras con alguien cercano.",
  "Cuenta un recuerdo que te haga sonreír. No leas: háblalo naturalmente.",
  "Explica algo que conoces muy bien, con tu ritmo normal y haciendo pausas."
];
export function VoiceClone(){
  const [voiceId,setVoiceId]=useState<string|null>(null),[available,setAvailable]=useState(true),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[recording,setRecording]=useState(false),[msg,setMsg]=useState(""),[err,setErr]=useState(""),[previewing,setPreviewing]=useState(false);
  const [samples,setSamples]=useState<File[]>([]); const rec=useRef<MediaRecorder|null>(null), chunks=useRef<Blob[]>([]), input=useRef<HTMLInputElement>(null), startedAt=useRef(0);
  useEffect(()=>{fetch('/api/voice/clone').then(r=>r.json()).then(d=>{setVoiceId(d.voiceId??null);setAvailable(d.cloningAvailable??true)}).catch(()=>{}).finally(()=>setLoading(false))},[]);
  async function toggleRecord(){
    if(recording){rec.current?.stop();setRecording(false);return;}
    try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{const seconds=(Date.now()-startedAt.current)/1000;stream.getTracks().forEach(t=>t.stop());if(seconds<8){setErr('La muestra fue muy corta. Habla al menos 8 segundos.');return}const blob=new Blob(chunks.current,{type:r.mimeType||'audio/webm'});setSamples(v=>[...v,new File([blob],`muestra-${v.length+1}.webm`,{type:blob.type})])};startedAt.current=Date.now();r.start();rec.current=r;setRecording(true);setErr("");}catch{setErr("Necesito permiso al micrófono para grabar tu voz.")}
  }
  async function create(){if(!samples.length)return;setWorking(true);setErr("");setMsg("");try{const fd=new FormData();samples.forEach(f=>fd.append('files',f));fd.append('consent','true');const r=await fetch('/api/voice/clone',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error||'No se pudo clonar');setVoiceId(d.voiceId);setMsg('Tu voz quedó activa en Eon.')}catch(e){setErr(e instanceof Error?e.message:'Error de conexión')}finally{setWorking(false)}}
  async function preview(){setPreviewing(true);setErr("");try{const r=await fetch("/api/voice/preview",{method:"POST"});if(!r.ok)throw new Error("No pude generar la prueba");const url=URL.createObjectURL(await r.blob());const a=new Audio(url);a.onended=()=>{URL.revokeObjectURL(url);setPreviewing(false)};await a.play()}catch(e){setPreviewing(false);setErr(e instanceof Error?e.message:"No pude reproducirla")}}
  async function remove(){setWorking(true);try{await fetch('/api/voice/clone',{method:'DELETE'});setVoiceId(null);setSamples([]);setMsg('Tu clon fue eliminado.')}catch{setErr('No pude eliminar el clon.')}finally{setWorking(false)}}
  const idx=Math.min(samples.length,2);
  return <FadeInOnScroll delay={.14}><input ref={input} hidden type="file" accept="audio/*" multiple onChange={e=>setSamples(Array.from(e.target.files??[]))}/><Card><p className="eon-page-kicker">Identidad de voz</p><CardTitle>Haz que Eon pueda hablar con tu voz.</CardTitle><CardDescription className="mt-1">Tres muestras naturales suelen capturar mejor tu ritmo, pausas y pronunciación que un audio leído de corrido.</CardDescription>{loading?<p className="mt-4 text-sm">Cargando…</p>:voiceId?<div className="voice-studio-active"><span>✓</span><div><b>Tu voz está activa</b><small>Puedes reemplazarla o eliminarla cuando quieras.</small></div><div className="flex gap-2"><Button variant="ghost" onClick={preview} loading={previewing}>Escuchar mi clon</Button><Button variant="ghost" onClick={remove} loading={working}>Eliminar clon</Button></div></div>:<div className="voice-studio"><div className={`voice-recorder ${recording?'recording':''}`}><div className="voice-wave">{[1,2,3,4,5,6,7].map(x=><i key={x}/>)}</div><small>Muestra {Math.min(samples.length+1,3)} de 3</small><h3>{PROMPTS[idx]}</h3><Button onClick={toggleRecord}>{recording?'Terminar muestra':'Grabar muestra'}</Button></div><div className="voice-samples">{[0,1,2].map(i=><span key={i} className={samples[i]?'done':''}>{samples[i]?'✓':'○'} Muestra {i+1}</span>)}</div><div className="flex flex-wrap gap-2"><Button onClick={create} loading={working} disabled={!samples.length||!available}>Crear mi voz</Button><Button variant="ghost" onClick={()=>input.current?.click()}>Subir audios</Button></div></div>}{msg&&<p className="mt-3 text-sm text-[var(--et-success)]">{msg}</p>}{err&&<p className="mt-3 text-sm text-[var(--et-danger)]">{err}</p>}<p className="mt-3 text-[10px] leading-relaxed text-[var(--et-text-faint)]">Al crear el clon confirmas que las muestras son de tu propia voz y autorizas su procesamiento para esta función. Puedes eliminarlo desde aquí.</p></Card></FadeInOnScroll>;
}
