-- AUTO-GENERATED by scripts/build-tenant-init.mjs — do not edit by hand.
-- Applied to every new per-user Neon branch during provisioning.
CREATE EXTENSION IF NOT EXISTS vector;
--> statement-breakpoint
CREATE TYPE "public"."memory_source" AS ENUM('manual', 'conversation', 'imported', 'scheduled');--> statement-breakpoint
CREATE TYPE "public"."memory_type" AS ENUM('text', 'audio', 'video', 'photo', 'document');--> statement-breakpoint
CREATE TYPE "public"."message_role" AS ENUM('user', 'ai');--> statement-breakpoint
CREATE TYPE "public"."voice_clone_type" AS ENUM('instant', 'professional');--> statement-breakpoint
CREATE TABLE "conversations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"started_at" timestamp with time zone DEFAULT now() NOT NULL,
	"summary" text,
	"message_count" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "daily_prompts_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"prompt" text,
	"prompted_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_response" text,
	"processed" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "documents" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text,
	"blob_url" text,
	"extracted_text" text,
	"embedding" vector(3072),
	"doc_type" text,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "memories" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" "memory_type" DEFAULT 'text' NOT NULL,
	"title" text,
	"content_text" text,
	"blob_url" text,
	"captured_at" timestamp with time zone,
	"category" text,
	"tags" text[],
	"embedding" vector(3072),
	"importance_score" real DEFAULT 0.5,
	"source" "memory_source" DEFAULT 'manual' NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"conversation_id" uuid NOT NULL,
	"role" "message_role" NOT NULL,
	"content" text NOT NULL,
	"audio_url" text,
	"embedding" vector(3072),
	"tokens" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "personality_profile" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"system_prompt" text NOT NULL,
	"values" jsonb,
	"communication_style" jsonb,
	"memories_summary" text,
	"version" integer DEFAULT 1 NOT NULL,
	"last_updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "relationships" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"relation" text,
	"photos_urls" text[],
	"notes" text,
	"important_dates" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "settings" (
	"id" integer PRIMARY KEY DEFAULT 1 NOT NULL,
	"data" jsonb DEFAULT '{}'::jsonb NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "timeline_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"event_date" date,
	"title" text,
	"description" text,
	"people_involved" text[],
	"location" text,
	"photos_urls" text[],
	"importance" real DEFAULT 0.5,
	"embedding" vector(3072),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "voice_clones" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"elevenlabs_voice_id" text,
	"type" "voice_clone_type" DEFAULT 'instant' NOT NULL,
	"audio_samples_urls" text[],
	"active" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_conversation_id_conversations_id_fk" FOREIGN KEY ("conversation_id") REFERENCES "public"."conversations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "memories_created_idx" ON "memories" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "messages_conversation_idx" ON "messages" USING btree ("conversation_id");
